<template>
    <div class="">
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'authentication_ids'" 
            :queryName="'认证状态'" 
            :queryList="configForm.authentication"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'name'" 
            :queryName="'姓名'"></query-search-input>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'phone'" 
            :queryName="'电话'"></query-search-input>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'return_msg'" 
            :queryName="'回访信息'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'working_status_ids'" 
            :queryName="'接单状态'" 
            :queryList="configForm.working_status"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'remarks'" 
            :queryName="'备注（商家情况）'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'service_category_ids'" 
            :queryName="'职业类型'" 
            :queryList="configForm.service_category"></query-search-list>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'service_type_ids'" 
            :queryName="'服务类型'" 
            :queryList="configForm.service_type"></query-search-list>     
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'service_crowd_ids'" 
            :queryName="'可服务人群'" 
            :queryList="configForm.service_crowd"></query-search-list>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'working_age_ids'" 
            :queryName="'工龄'" 
            :queryList="configForm.working_age"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'working_experience'" 
            :queryName="'工作经验'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'nation_ids'" 
            :queryName="'民族'" 
            :queryList="configForm.nation"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'birthplace'" 
            :queryName="'籍贯'"></query-search-input>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'identify'" 
            :queryName="'身份证号'"></query-search-input>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'address'" 
            :queryName="'地址'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'service_region_ids'" 
            :queryName="'服务地区'" 
            :queryList="configForm.service_region"></query-search-list>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'education_ids'" 
            :queryName="'教育程度'" 
            :queryList="configForm.education"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'urgent_phone'" 
            :queryName="'紧急联系人电话'"></query-search-input>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'bank_card'" 
            :queryName="'银行卡号'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'course_ids'" 
            :queryName="'参加培训'" 
            :queryList="configForm.course"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'teacher_comment'" 
            :queryName="'教师评语'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'paper_category_ids'" 
            :queryName="'技能证书标签'" 
            :queryList="configForm.paper_category"></query-search-list>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'source_ids'" 
            :queryName="'信息来源'" 
            :queryList="configForm.source"></query-search-list>
        <query-search-input
            :queryFrom="queryFrom"
            @updateTable="updateTable"
            :queryKey="'source_name'" 
            :queryName="'来源名称'"></query-search-input>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :queryKey="'manager_ids'" 
            :queryName="'创建人'" 
            :queryList="configForm.manager"></query-search-list>
        <query-search-list
            :queryFrom="queryFrom"
            @updateTable="updateTable" 
            :isSingleQuery="true"
            :queryKey="'updated_type_ids'" 
            :queryName="'更新时间'" 
            :queryList="configForm.updated_type"></query-search-list>
    </div>
</template>
<script>
import {
    querySearchList,
    querySearchInput,
} from './queryComponent/index.js'

import {queryUpdated_at} from '../interface/query.js'
export default {
    data(){
        return {
            setConfigForm: [],//本地接收的搜索config字段
            queryUpdated_at,
        }
    },
    components: {
        querySearchList,
        querySearchInput,
    },
    computed:{
        configForm(){
            return this.$store.state.operateModule.configForm
        }
    },
    methods: {
        // 更新表格数据
        updateTable(){
            this.$emit('updateTable')
        }
    },
}
</script>
<style lang="scss" scoped>

</style>


